version: '3.8'

services:
  # База данных
  mongodb:
    image: mongo:6
    container_name: lexigram-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - lexigram-network

  # User Service
  user-service:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    container_name: lexigram-user-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/lexigram?authSource=admin
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - lexigram-network

  # Translation Service
  translation-service:
    build:
      context: ./services/translation
      dockerfile: Dockerfile
    container_name: lexigram-translation-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
    networks:
      - lexigram-network

  # Bot
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: lexigram-bot
    environment:
      - NODE_ENV=development
      - BOT_TOKEN=${BOT_TOKEN}
      - USER_SERVICE_URL=http://user-service:3000
      - TRANSLATION_SERVICE_URL=http://translation-service:3002
    depends_on:
      - user-service
      - translation-service
    networks:
      - lexigram-network

volumes:
  mongodb_data:

networks:
  lexigram-network:
    driver: bridge 